
<?php

Etape::addQuery('SELECT_ID_ETAPE', 'SELECT IDETAPE FROM ETAPE WHERE IDETAPE = :id');
Etape::addQuery('SELECT_NOM_ETAPE', 'SELECT NOM FROM ETAPE WHERE IDETAPE = :id');
Etape::addQuery('SELECT_CODEPOSTAL', 'SELECT CODEPOSTAL FROM ETAPE WHERE IDETAPE = :id');

Etape::addQuery('CREER_ETAPE', 'INSERT INTO ETAPE (IDETAPE,NOM, CODEPOSTAL) VALUES (NULL,:nometape, 0)');

//donne le nombre d'étapes qui ont un nom donné
Etape::addQuery('NOMBRE_ETAPES', 'SELECT COUNT(ETAPE.IDETAPE) AS COUNT FROM ETAPE WHERE ETAPE.NOM LIKE :nometape');

//donne les étapes d'un trajet donné
Trajet::addQuery('SELECT_ETAPES', 'SELECT ETAPE.NOM AS NOM_ETAPES FROM ETAPE JOIN PASSERPAR ON ETAPE.IDETAPE = PASSERPAR.IDETAPE JOIN TRAJET ON TRAJET.IDTRAJET = PASSERPAR.IDTRAJET WHERE TRAJET.IDTRAJET = :id');

//donne le nombre d'étapes d'un trajet donné
Trajet::addQuery('SELECT_NOMBRE_ETAPES', 'SELECT COUNT(ETAPE.NOM) AS COUNT FROM ETAPE JOIN PASSERPAR ON ETAPE.IDETAPE = PASSERPAR.IDETAPE JOIN TRAJET ON TRAJET.IDTRAJET = PASSERPAR.IDTRAJET WHERE TRAJET.IDTRAJET = :id');

Trajet::addQuery('SELECT_ID_AVEC_NOM', 'SELECT ETAPE.IDETAPE AS ID_ETAPE FROM ETAPE WHERE ETAPE.NOM LIKE :nometape');

 ?>
