

<?php
//INSERT INTO `notifier` (`IDNOTIFICATION`, `IDUSER`) VALUES ('1', '5');
//SELECT USER.IDUSER FROM USER JOIN RESERVER ON USER.IDUSER = RESERVER.IDUSER WHERE RESERVER.IDTRAJET = '7' ;
// SELECT RESERVER.IDUSER FROM RESERVER WHERE RESERVER.IDTRAJET = '7' ;
// SELECT DISTINCT NOTIFICATION.NOTIFICATION FROM RESERVER JOIN NOTIFICATION ON RESERVER.IDTRAJET = NOTIFICATION.IDTRAJET WHERE NOTIFICATION.IDTRAJET = '7';
Notification::addQuery('SELECT_NOTIF_OF_USER', "SELECT NOTIFICATION FROM NOTIFICATION INNER JOIN NOTIFIER ON NOTIFICATION.IDNOTIFICATION = NOTIFIER.IDNOTIFICATION WHERE NOTIFIER.IDUSER = :iduser");
Notification::addQuery('SELECT_NOTIF_AND_IDNOTIFICATION_OF_USER', "SELECT NOTIFICATION, notification.IDNOTIFICATION FROM NOTIFICATION INNER JOIN NOTIFIER ON NOTIFICATION.IDNOTIFICATION = NOTIFIER.IDNOTIFICATION WHERE NOTIFIER.IDUSER = :iduser");

Notification::addQuery('CREATE_NOTIF_FOR_TRAJET',"INSERT INTO `notification` (`IDNOTIFICATION`, `INDICATION`, `NOTIFICATION`, `IDTRAJET`) VALUES (NULL, :notification, :idTrajet)");
Notification::addQuery('NOTIFIER_UN_USER',"INSERT INTO `notifier` (`IDNOTIFICATION`, `IDUSER`) VALUES (:idNotif, :idUser)");
//Notification::addQuery('CREATE_NOTIF_FOR_TRAJET_AND_RECUP_ID',"INSERT INTO `notification` (`IDNOTIFICATION`, `NOTIFICATION`, `IDTRAJET`) VALUES (NULL, :notification, :idTrajet); SELECT LAST_INSERT_ID() AS IDNOTIFICATION;");
Notification::addQuery('CREATE_NOTIF_FOR_TRAJET_AND_RECUP_ID',"INSERT INTO `notification` (`IDNOTIFICATION`, `INDICATION`, `NOTIFICATION`, `IDTRAJET`) VALUES (NULL, :indication, :notification , :idTrajet); SELECT LAST_INSERT_ID() AS IDNOTIFICATION;");

Notification::addQuery('DELETE_NOTIFIER', "DELETE FROM `notifier` WHERE `notifier`.`IDNOTIFICATION` = :idNotif AND `notifier`.`IDUSER` = :idUser");
Notification::addQuery('SELECT_INDICATION', "SELECT INDICATION FROM notification WHERE `IDNOTIFICATION` = :idNotif");

/*//AIDE SQL
Notification::addQuery('CREATE_NOTIF_FOR_TRAJET_AND_RECUP_ID',"INSERT INTO `notification` (`IDNOTIFICATION`, `INDICATION`, `NOTIFICATION`, `IDTRAJET`) VALUES (NULL, :indication, :notification , :idTrajet); SELECT LAST_INSERT_ID() AS IDNOTIFICATION;");

Notifier l'user :id
INSERT INTO `notifier` (`IDNOTIFICATION`, `IDUSER`, `ACTIF`) VALUES ('idnotification', 'iduser');
Selectionne user d'un trajet
User::addQuery('USERS_OF_A_TRAJET', 'SELECT USER.IDUSER FROM USER JOIN RESERVER ON USER.IDUSER = RESERVER.IDUSER JOIN TRAJET ON RESERVER.IDUSER = USER.IDUSER WHERE TRAJET.IDTRAJET = :idtrajet;');
SELECT * FROM notifier WHERE notifier.IDUSER IN (SELECT USER.IDUSER FROM USER JOIN RESERVER ON USER.IDUSER = RESERVER.IDUSER JOIN TRAJET ON RESERVER.IDUSER = USER.IDUSER WHERE TRAJET.IDTRAJET = 1)

//NE FONCTIONNE PAS:
INSERT INTO `notifier` (`IDNOTIFICATION`, `IDUSER`, `ACTIF`) VALUES ('idnotification', 'iduser' IN (SELECT USER.IDUSER FROM USER JOIN RESERVER ON USER.IDUSER = RESERVER.IDUSER JOIN TRAJET ON RESERVER.IDUSER = USER.IDUSER WHERE TRAJET.IDTRAJET = 1));


*/
//a tester
Notification::addQuery('SELECT_TRAJET_OF_NOTIF', "SELECT TRAJET FROM TRAJET INNER JOIN NOTIFICATION ON NOTIFICATION.IDTRAJET = TRAJET.IDTRAJET WHERE NOTIFICATION.IDTRAJET = :idTrajet");


?>
