
<?php

Voiture::addQuery('SELECT_IDPROPRIETAIRE', 'SELECT IDPROPRIETAIRE FROM VOITURE WHERE IDVOITURE = :id');
Voiture::addQuery('SELECT_MARQUE_VOITURE', 'SELECT MARQUE FROM VOITURE WHERE IDVOITURE = :id');
Voiture::addQuery('SELECT_MODELE_VOITURE', 'SELECT MODELE FROM VOITURE WHERE IDVOITURE = :id');
Voiture::addQuery('SELECT_NBXPLACE_VOITURE', 'SELECT NBXPLACE FROM VOITURE WHERE IDVOITURE = :id');
Voiture::addQuery('SELECT_COULEUR_VOITURE', 'SELECT COULEUR FROM VOITURE WHERE IDVOITURE = :id');



 ?>